#!/bin/bash
#set -x

data=`curl -X POST -s  http://10.199.54.202/hudson/ajaxExecutors | tidy -numeric -q -ashtml --show-warnings no  | grep -v DOCTYPE | sed -e 's/xml.*$/>/' | grep -v title`
#if [ 0 -lt `curl -X POST -s  http://10.199.54.202/hudson/ajaxExecutors | tidy -i  2>/dev/null | grep -i building | wc -l` ] ; then
if [ 0 -lt `echo $data | grep -i Sigmaplus_Build | wc -l` ] ; then
    rtime=`curl -X POST -s  http://10.199.54.202/hudson/ajaxExecutors | tidy -numeric -q -ashtml --show-warnings no  | grep -v DOCTYPE | sed -e 's/xml.*$/>/' | grep -v title | grep 'Estimated remaining time' |cut -d':' -f2 |sed -e 's/^ //g' | awk '{print $1}'`
    echo '<span color="red"> b ('`echo $rtime`') </span>'
else
    echo '<span color="green"> w </span>'
fi